/*
  ┌──────────────────────────────────────────────────────────────────────────┐
  │  WIKIRACE ARTICLES  —  static pool of ~440 Wikipedia article titles     │
  ├──────────────────────────────────────────────────────────────────────────┤
  │                                                                          │
  │   IIFE on load ──► defines global.WikiraceArticles = string[]            │
  │                          │                                               │
  │                          └─ mirror of assets/json/articles.json          │
  │                              (file:// can't fetch JSON — this is the     │
  │                               runtime source of truth)                   │
  │                                                                          │
  │   Categories (rough): scientists, artists, musicians, writers, places,   │
  │     foods, animals, sports, history, mythology, science topics, etc.    │
  │                                                                          │
  │   Titles must match en.wikipedia.org canonical names exactly             │
  │   (case-sensitive). Bad entries get cached as failed and filtered out    │
  │   at race time (see WikiraceAPI.setCachedFailed).                        │
  │                                                                          │
  │   Consumers:                                                             │
  │     WikiraceAPI.warmCache         ──► fetches pageviews for each         │
  │     WikiraceAPI.getVerifiedArticles ──► subset with fresh +ve avg        │
  │     WikiraceRealHorses.generateRealRace ──► picks 18 → 9 horses          │
  │     WikiraceGame.ensureLiveData / sampleArticles                         │
  │     page.js cache UI                                                     │
  │                                                                          │
  │   Exports (window.WikiraceArticles): string[]                            │
  │   External deps: none                                                    │
  │                                                                          │
  └──────────────────────────────────────────────────────────────────────────┘

  CODE (terse, AI-readable):
  data: global.WikiraceArticles=string[~440] of en.wikipedia canonical titles (case-sensitive); categories: scientists/artists/composers/writers/historical/celebrities/tech-political/athletes/creators/landmarks/geography/cities/countries/foods/animals/tech/films/science/events/CS/comedians/saints/baseball; mirror of assets/json/articles.json (file:// can't fetch)
*/

(function (global) {
  // 440 recognizable Wikipedia article titles for the horse-racing pool.
  // Mirror of assets/json/articles.json — keep in sync. The runtime can't
  // fetch the JSON over file://, so this file is the source of truth at run.
  // Titles must match en.wikipedia.org canonical names exactly (case-sensitive).
  // Failed lookups are persisted in cache and filtered out at race time, so
  // a couple of broken entries here won't break the game.
  global.WikiraceArticles = [
    // scientists & thinkers
    'Albert Einstein',
    'Isaac Newton',
    'Charles Darwin',
    'Galileo Galilei',
    'Nikola Tesla',
    'Marie Curie',
    'Stephen Hawking',
    'Sigmund Freud',
    'Plato',
    'Aristotle',
    'Socrates',
    'Confucius',
    'Alan Turing',
    'Pythagoras',
    'Archimedes',
    'Carl Sagan',
    'Richard Feynman',
    'Niels Bohr',
    'Werner Heisenberg',
    'Erwin Schrödinger',
    'René Descartes',
    'Friedrich Nietzsche',
    'Karl Marx',
    'Immanuel Kant',

    // artists
    'Leonardo da Vinci',
    'Vincent van Gogh',
    'Pablo Picasso',
    'Claude Monet',
    'Salvador Dalí',
    'Frida Kahlo',
    'Michelangelo',
    'Andy Warhol',
    'Mona Lisa',
    'Rembrandt',
    'Johannes Vermeer',
    'Raphael',
    'Caravaggio',
    'Henri Matisse',
    'Jackson Pollock',
    'Banksy',
    "Georgia O'Keeffe",
    'Edvard Munch',

    // composers & writers
    'Wolfgang Amadeus Mozart',
    'Ludwig van Beethoven',
    'Johann Sebastian Bach',
    'Frédéric Chopin',
    'William Shakespeare',
    'Edgar Allan Poe',
    'Mark Twain',
    'Charles Dickens',
    'Jane Austen',
    'Ernest Hemingway',
    'Pyotr Ilyich Tchaikovsky',
    'Franz Schubert',
    'Antonio Vivaldi',
    'Richard Wagner',
    'Leo Tolstoy',
    'Fyodor Dostoevsky',
    'J. R. R. Tolkien',
    'George Orwell',
    'Agatha Christie',
    'Oscar Wilde',

    // historical / political
    'Napoleon',
    'Cleopatra',
    'Julius Caesar',
    'Alexander the Great',
    'Genghis Khan',
    'Abraham Lincoln',
    'George Washington',
    'Winston Churchill',
    'Joseph Stalin',
    'Adolf Hitler',
    'Mahatma Gandhi',
    'Nelson Mandela',
    'Martin Luther King Jr.',
    'Mother Teresa',
    'Joan of Arc',
    'Anne Frank',
    'Christopher Columbus',
    'Henry VIII',
    'Queen Elizabeth II',
    'Ronald Reagan',
    'John F. Kennedy',
    'Theodore Roosevelt',
    'Franklin D. Roosevelt',
    'Thomas Jefferson',
    'Benjamin Franklin',
    'Mao Zedong',
    'Vladimir Lenin',
    'Catherine the Great',
    'Tutankhamun',
    'Ramesses II',
    'Marie Antoinette',
    'Charlemagne',
    'Vlad the Impaler',
    'Hernán Cortés',
    'Marco Polo',
    'Saladin',
    'Suleiman the Magnificent',
    'Pope John Paul II',

    // modern celebrities
    'Marilyn Monroe',
    'Audrey Hepburn',
    'Charlie Chaplin',
    'Walt Disney',
    'Princess Diana',
    'Bob Dylan',
    'Elvis Presley',
    'The Beatles',
    'John Lennon',
    'Michael Jackson',
    'Madonna (entertainer)',
    'Taylor Swift',
    'Beyoncé',
    'Eminem',
    'Bob Marley',
    'Jimi Hendrix',
    'Freddie Mercury',
    'Frank Sinatra',
    'Whitney Houston',
    'Prince (musician)',
    'David Bowie',
    'Mariah Carey',
    'Lady Gaga',
    'Rihanna',
    'Drake (musician)',
    'Kanye West',
    'Bruno Mars',
    'Justin Bieber',
    'Britney Spears',
    'Adele',
    'Ed Sheeran',
    'Robin Williams',
    'Heath Ledger',
    'Kim Kardashian',

    // modern tech / political
    'Steve Jobs',
    'Bill Gates',
    'Elon Musk',
    'Barack Obama',
    'Donald Trump',
    'Mark Zuckerberg',
    'Jeff Bezos',
    'Joe Biden',
    'Hillary Clinton',
    'Vladimir Putin',

    // athletes
    'Muhammad Ali',
    'LeBron James',
    'Michael Jordan',
    'Serena Williams',
    'Cristiano Ronaldo',
    'Lionel Messi',
    'Tom Brady',
    'Tiger Woods',
    'Bruce Lee',
    'Pelé',
    'Diego Maradona',
    'Kobe Bryant',
    'Babe Ruth',
    'Roger Federer',
    'Rafael Nadal',
    'Usain Bolt',
    'Mike Tyson',
    'Wayne Gretzky',

    // creators (writers / directors)
    'Stephen King',
    'J. K. Rowling',
    'Steven Spielberg',
    'Alfred Hitchcock',
    'Quentin Tarantino',
    'George Lucas',
    'James Cameron',
    'Christopher Nolan',
    'Hayao Miyazaki',
    'Martin Scorsese',

    // landmarks
    'Eiffel Tower',
    'Great Wall of China',
    'Mount Everest',
    'Great Pyramid of Giza',
    'Colosseum',
    'Stonehenge',
    'Statue of Liberty',
    'Taj Mahal',
    'Machu Picchu',
    'Niagara Falls',
    'Grand Canyon',
    'Mount Fuji',
    'Big Ben',
    'Leaning Tower of Pisa',
    'Great Sphinx of Giza',
    'Acropolis of Athens',
    'Petra',
    'Sagrada Família',
    'Buckingham Palace',
    'White House',
    'Empire State Building',
    'Sydney Opera House',
    'Hollywood Sign',
    'Burj Khalifa',
    'Notre-Dame de Paris',
    'Brandenburg Gate',
    'Christ the Redeemer (statue)',
    'Angkor Wat',

    // geography
    'Sahara',
    'Amazon rainforest',
    'Antarctica',
    'Iceland',
    'Hawaii',
    'Pacific Ocean',
    'Atlantic Ocean',
    'Nile',
    'Mississippi River',
    'Mount Kilimanjaro',
    'K2',
    'Dead Sea',
    'Lake Baikal',
    'Indian Ocean',
    'Arctic Ocean',
    'Mediterranean Sea',
    'Andes',
    'Himalayas',

    // cities
    'Tokyo',
    'New York City',
    'Paris',
    'London',
    'Rome',
    'Berlin',
    'Moscow',
    'Rio de Janeiro',
    'Los Angeles',
    'Sydney',
    'Beijing',
    'Shanghai',
    'Hong Kong',
    'Dubai',
    'Singapore',
    'Mumbai',
    'Cairo',
    'Istanbul',
    'Bangkok',
    'Toronto',

    // countries
    'Egypt',
    'Japan',
    'India',
    'China',
    'Brazil',
    'Russia',
    'United States',
    'Germany',
    'France',
    'Italy',
    'Mexico',
    'Canada',
    'Australia',
    'United Kingdom',
    'Spain',
    'Greece',
    'Turkey',
    'South Africa',
    'Argentina',
    'South Korea',
    'North Korea',
    'Saudi Arabia',

    // foods & drinks
    'Pizza',
    'Sushi',
    'Hamburger',
    'Bread',
    'Pasta',
    'Rice',
    'Tea',
    'Coffee',
    'Chocolate',
    'Cheese',
    'Banana',
    'Wine',
    'Beer',
    'Whisky',
    'Honey',
    'Milk',
    'Ice cream',
    'Hot dog',
    'Taco',
    'Curry',
    'Apple',
    'Strawberry',
    'Tomato',
    'Steak',

    // animals
    'Cat',
    'Dog',
    'Lion',
    'Tiger',
    'Elephant',
    'Wolf',
    'Horse',
    'Whale',
    'Dolphin',
    'Shark',
    'Eagle',
    'Spider',
    'Snake',
    'Penguin',
    'Bear',
    'Cattle',
    'Pig',
    'Chicken',
    'Fox',
    'Rabbit',
    'Squirrel',
    'Owl',
    'Octopus',
    'Crocodile',
    'Frog',
    'Butterfly',
    'Bee',
    'Ant',
    'Kangaroo',
    'Giraffe',

    // tech / inventions
    'Internet',
    'Computer',
    'Smartphone',
    'Telephone',
    'Airplane',
    'Car',
    'Television',
    'Camera',
    'Robot',
    'Bicycle',
    'Train',
    'Ship',
    'Rocket',
    'Laser',
    'X-ray',
    'Battery (electricity)',
    'Clock',
    'Printing press',

    // films / TV / characters
    'Star Wars',
    'The Godfather',
    'Titanic (1997 film)',
    'The Matrix',
    'Pulp Fiction',
    'Inception',
    'Avatar (2009 film)',
    'Harry Potter',
    'Sherlock Holmes',
    'Mickey Mouse',
    'The Lord of the Rings',
    'Forrest Gump',
    'Jurassic Park (film)',
    'Casablanca (film)',
    'The Lion King',
    'Frozen (2013 film)',
    'The Wizard of Oz (1939 film)',
    'Spider-Man',
    'Batman',
    'Superman',

    // science
    'Gravity',
    'DNA',
    'Black hole',
    'Big Bang',
    'Evolution',
    'Quantum mechanics',
    'Theory of relativity',
    'Solar System',
    'Moon',
    'Sun',
    'Earth',
    'Universe',
    'Mars',
    'Jupiter',
    'Saturn',
    'Venus',
    'Mercury (planet)',
    'Pluto',
    'Galaxy',
    'Atom',
    'Photosynthesis',
    'Cell (biology)',
    'Vaccine',
    'Periodic table',

    // events & concepts
    'World War II',
    'World War I',
    'Apollo 11',
    'Cold War',
    'Roman Empire',
    'Christianity',
    'Islam',
    'Buddhism',
    'Music',
    'Art',
    'Mathematics',
    'Philosophy',
    'Renaissance',
    'Industrial Revolution',
    'French Revolution',
    'American Revolution',
    'The Holocaust',
    'September 11 attacks',
    'Hinduism',
    'Judaism',
    'Capitalism',
    'Democracy',
    'Science',
    'Religion',

    // computer science
    'Linux',
    'Unix',
    'Linus Torvalds',
    'Dennis Ritchie',
    'Donald Knuth',
    'Tim Berners-Lee',
    'Ada Lovelace',
    'Grace Hopper',
    'John von Neumann',
    'Claude Shannon',

    // comedians
    'George Carlin',
    'Richard Pryor',
    'Eddie Murphy',
    'Jerry Seinfeld',
    'Dave Chappelle',
    'Joan Rivers',
    'Lucille Ball',
    'Bob Hope',
    'Steve Martin',
    'John Cleese',

    // saints
    'Saint Peter',
    'Paul the Apostle',
    'Saint Patrick',
    'Francis of Assisi',
    'Augustine of Hippo',
    'Thomas Aquinas',
    'Saint Nicholas',
    'Anthony of Padua',
    'Saint Christopher',
    'Mary, mother of Jesus',

    // baseball
    'Jackie Robinson',
    'Lou Gehrig',
    'Joe DiMaggio',
    'Ted Williams',
    'Hank Aaron',
    'Mickey Mantle',
    'Willie Mays',
    'Derek Jeter',
    'Barry Bonds',
    'Shohei Ohtani',
  ];
})(window);
